name: Create release

on:
  workflow_dispatch:

jobs:
  verify-name:
    name: Test1
    runs-on: ubuntu-latest
    steps:
      - name: "Try get data"
        run: |
          echo "test GH"
  release:
    environment: "custom-prod"
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          tag: "2.4.0" #${{ github.ref_name }}
        # run: |
        #   echo $GITHUB_REPOSITORY
        #   gh release create "$tag" \
        #       --repo="$GITHUB_REPOSITORY" \
        #       --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
        #       --generate-notes
        uses: softprops/action-gh-release@v1
        with:
          # body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: "Version ${{ env.tag }}"
          repository: "quic-bhushans/aimet" # ${{ env.PUBLIC_REPO }}
          tag_name: "${{ env.tag }}"
          target_commitish: "${{ github.ref_name }}" # ${{ env.RELEASE_BRANCH }}
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: "${GITHUB_TOKEN}"
          generate_release_notes: true
              
