name: Test env name

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AIMET version to release"
        required: true
        type: string
env:
  RELEASE_BRANCH: "release-aimet-${{ inputs.version }}"

jobs:
  checklist:
    name: Validate version and release branch exists
    runs-on: ubuntu-latest
    steps:
      - name: Test name
        run: |
          echo Specified release version $RELEASE_BRANCH
          version_increments=`echo ${{ inputs.version }} | grep -o '\.' | wc -l`
          echo $version_increments
          if [[ $version_increments != 2 ]]; then
              echo "Incorrect version specified. Version must follow Semantic versioning i.e. <major>.<minor>.<patch>"
              echo "Refer to https://semver.org/"
              exit 1
          fi
          
      

  
