name: Test env name

on:
  workflow_dispatch:
    inputs:
      version:
        description: "AIMET version to release"
        required: true
        type: string
env:
  RELEASE_BRANCH: "release-aimet"
  INTERNAL_REPO_DIR: "aimet-repo"

jobs:
  checklist:
    name: Validate version and release branch exists
    runs-on: ubuntu-latest
    steps:
      - name: Test name
        run: |
          echo Specified release version $RELEASE_BRANCH
          version_increments=`echo ${{ inputs.version }} | grep -o '\.' | wc -l`
          echo $version_increments
          if [[ $version_increments != 2 ]]; then
              echo "Incorrect version specified. Version must follow Semantic versioning i.e. <major>.<minor>.<patch>"
              echo "Refer to https://semver.org/"
              exit 1
          fi
      - name: Set release branch env
        run: |
           branch_suffix=`echo "2.3.0" | cut -d'.' -f 1,2`
           echo $branch_suffix
           RELEASE_BRANCH="${{ env.RELEASE_BRANCH }}-${branch_suffx}"
           echo $RELEASE_BRANCH
           echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> $GITHUB_ENV
      - name: Checkout internal repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.RELEASE_BRANCH }}
          path: ${{ env.INTERNAL_REPO_DIR }}
          fetch-depth: 0
      - name:
        run: |
          echo Specified release version $RELEASE_BRANCH
          cat packaging/version.txt
          
      

  
