name: Test workflow call

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - develop

  workflow_call:
    inputs:
      src_branch:
        description: "Internal source branch to sync"
        required: false
        default: "develop"
        type: string
      dst_branch:
        description: "External destination branch to sync"
        required: false
        default: "develop"
        type: string

env:
  TEST: "value of var is TEST"

jobs:

  set_variables:
    runs-on: ubuntu-latest
    outputs:
      branch2: ${{ steps.step2.outputs.branch2 }}
      src_branch: ${{ steps.step1.env.SRC_BRANCH }}
    steps:
      - name: "Set environment variables"
        id: step1
        run: |
          echo "REF: ${{ github.ref_name }}"
          echo "Var: ${{ env.TEST }}"
          echo "branch name: ${{ github.ref_name }}"
          echo "EVENT NAME: " ${{ github.event_name }}
          if [[ ${{ github.event_name }} == "push" ]]; then
            echo "In push event"
            echo "SRC_BRANCH=${{ env.DEFAULT_SRC_BRANCH }}" >> $GITHUB_ENV
            echo "DST_BRANCH=${{ env.DEFAULT_DST_BRANCH }}" >> $GITHUB_ENV
          else
            echo "In non push event"
            a_var="A VAR"
            echo $a_var
            SRC_BRANCH="${{ inputs.src_branch }}"
          fi
          echo src: $SRC_BRANCH
      - name: "Get inputs"
        id: step2
        run: |
          echo "EVENT NAME: " ${{ github.event_name }}
          echo "inputs: src_branch:" $SRC_BRANCH
          echo "branch2=hello" >> "$GITHUB_OUTPUT"
  read_variables:
    runs-on: ubuntu-latest
    needs: set_variables
    steps:
      - name: "Read vars"
        run: |
          echo "Var: ${{ needs.set_variables.outputs.branch2 }}"
          echo "Var: ${{ needs.set_variables.outputs.src_branch }}"
