name: Workflow call

on:

  workflow_dispatch:
    inputs:
      src_branch:
        description: "Internal source branch to sync"
        required: false
        default: "develop"
        type: string
      dst_branch:
        description: "External destination branch to sync"
        required: false
        default: "develop"
        type: string

jobs:

  job1:
    if: ${{ inputs.src_branch == 'develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: "run1"
        run: |
          echo "running on src_branch == develop"
  job2:
    needs: job1
    if: always() && needs.build.result == 'success' || needs.build.result == 'skipped'
    runs-on: ubuntu-latest
    steps:
      - name: "run1"
        run: |
          echo "running on job2"
    
  # call_vars:
  #   uses: ./.github/workflows/workflow_call.yml
  #   with:
  #     src_branch: ${{ inputs.src_branch }}
  #     dst_branch: ${{ inputs.dst_branch }}
